### ISSUE TITLE
'authorize' callback function not triggered

### ISSUE THREAD

**Issue by asmann89** [auth0/auth0-cordova#102]
I'm using auth0-cordova to trigger universal login with the 'authorize' function, but the callback giving (err, authResult) is never triggered. The webview is successfully closed, and from the auth0 logs I can see that the login was successful. Additionally, I see the following error in the xcode console:

```
2019-04-08 13:43:10.651524-0600 O2T[51241:2885308] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = Users;
    srvr = "o2t.eu.auth0.com";
    sync = syna;
}
```

From reading through community posts, it seems people have resolved this error in the past by setting their auth0 application type to "Native". I tried this but still get the same error. What might be going on here?

### Environment

- Version of `auth0-cordova` used: 0.3.0
- Version of Cordova used: 6.5.0

### Reproduction

1) Click to login through auth0
2) Redirected to universal login page 
3) login through auth0
4) Redirected back to app
5) Observe error in xcode console, observe that authorize callback was not triggered

```
const authOptions = { 
  responseType: "id_token token",
  scope: "openid profile",
}
```

```
      this.cordovaAuth = new Auth0Cordova({
        clientId: config.auth0ClientId,
        domain: config.auth0Domain,
        packageIdentifier: config.auth0PackageIdentifier,
      })  

```

```
this.cordovaAuth.authorize(authOptions, (err, result) => {
    console.log("AUTHORIZE CALLBACK")
})
```

**Comment by tommybananas** [comment]
@asmann89 figure this out at all?

**Comment by asmann89** [comment]
Yes, it turned out to be an advanced configuration switch in the Auth0 dashboard. The Auth0 support team helped to figure it out, but I also wonder if the documentation might be improved to show the relationships between the different APIs / libraries and the dashboard configuration
