### ISSUE TITLE
Module not found: Error: Can't resolve 'crypto' in 'C://mypc/path/node_module/@auth0\cordova\src'

### ISSUE THREAD

**Issue by cnguyenp** [auth0/auth0-cordova#107]
### Description

Hi, I am trying to run auth0/cordova with Ionic 4, but I have no luck. 
I am using v0.3.0.
I keep saying: `Module not found: Error: Can't resolve 'crypto' in 'D:\myproject\path\node_modules\@auth0\cordova\src'`

What do I need?

### Prerequisites

- [x] I have checked the [README documentation](https://github.com/auth0/auth0-cordova/blob/master/README.md).
- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0-cordova/issues) and [PRs](https://github.com/auth0/auth0-cordova/pulls).
- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\cng\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic 3.1.3, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 10 other plugins)

System:

   NodeJS : v9.11.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

### Reproduction
ng build
ionic cordova run android

both of these will produce the error.

**Comment by ymphyow** [comment]
Hello! I am facing the same issue. May I know how you solved it out.  I even got another error "TypeError: crypto.randomBytes is not a function". Many Thanks
