### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by ippeiukai** [auth0/auth0-cordova#109]
### Describe the problem you'd like to have solved

As described in https://github.com/auth0/auth0-cordova/issues/88#issuecomment-534915058, auth0-cordova currently depends on `crypto` module which is not generally available for web apps and near impossible to setup for Angular users.

### Describe the ideal solution

auth0-cordova should instead depends on alternative modules such as crypto-browserify or standard Web Cryptography API (https://www.w3.org/TR/WebCryptoAPI/).

### Alternatives and current work-arounds

Following alternatives are available, but not pretty:
- patching auth0-cordova to use crypto-browserify (https://github.com/auth0/auth0-cordova/issues/72#issuecomment-362174798, https://github.com/auth0/auth0-cordova/compare/master...stetsmando:master)
- patching inside node_modules with postinstall hook (https://github.com/auth0/auth0-cordova/issues/88#issuecomment-405901202)
- Instead of using standard Angular CLI, one might be able to setup own webpack configuration...

**Comment by ippeiukai** [comment]
> If you have not received a response for our team (apologies for the delay) and this is still a blocker, please reply with additional information or just a ping.

PING!

**Comment by Widcket** [comment]
Hi @ippeiukai, apologies for the delay. You can use a custom Webpack configuration to enable a `crypto` polyfill. Check out the [Ionic 4 QuickStart](https://auth0.com/docs/quickstart/native/ionic4/01-login#install-the-dependencies) for detailed instructions.

**Comment by ippeiukai** [comment]
Ah, there is a new doc then. Thanks!

(↓ I just give it a link)
https://github.com/auth0/docs/pull/8063
