### ISSUE TITLE
Login screen hangs after entering credentials

### ISSUE THREAD

**Issue by victororlyk** [auth0/auth0-cordova#118]
### Description
Work with ionic + react + auth0
After entering credentials i am not hang on the screen with infinitly loading spinner.
basically the issue is 
https://github.com/auth0/auth0-cordova/issues/58
the state described abode is seen in this comment
https://github.com/auth0/auth0-cordova/issues/31#issuecomment-304068718
and after we close it in auth0 we see logged in (and after starting new app we are actually logged and now see second state)
https://github.com/auth0/auth0-cordova/issues/31#issuecomment-304212046
> Provide a clear and concise description of the issue, including what you expected to happen.
After entering credentials i must be redirected to home page.
### Reproduction
follow this tutorial with react+ ionic + capacitor
https://manage.auth0.com/dashboard/us/rapid-recs/applications/PatFM09YPFrlDdS31IFnlkvIE9U1mFx5/quickstart

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
```
import React, { useEffect, useState } from 'react';
import { Plugins } from '@capacitor/core';
import * as auth0 from 'auth0-js';

import { conf } from 'Auth_Config';

const Auth0Cordova = require('@auth0/cordova');

const Auth0 = new auth0.WebAuth(conf);
const Client = new Auth0Cordova(conf);
const storage = Plugins.Storage;

const Auth: React.FC = () => {
const [logged, setLogged] = useState(false)
  const login = () => {
    const options = {
      domain: conf.domain,
      clientId: conf.clientId,
      scope: 'openid profile offline_access',
      responseType: 'token id_token',
    };

    Client.authorize(options, async (err: any, authResult: any) => {
      if (err) {
        console.log(err, 'err');
      }
setLogged(true)
 

      });
    });
  };


  useEffect(() => {
if(!logged){

    login();
}
  }, []);
  
  return null;
};

export default Auth;

```

and of course in index.js
```

function main() {
  function handlerUrl(url: string) {
      Auth0Cordova.onRedirectUri(url);
  }

  window.handleOpenURL = handlerUrl;
}

// init your application
document.addEventListener('deviceready', main);
```
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of this library used:** "^0.4.2",
- **Version of the platform or framework used, if applicable:** any ios
- **Other relevant versions (language, server software, OS, browser):** macOs, 
- **Other modules/plugins/libraries that might be involved:**"auth0-js": "^9.12.2",
    "cordova-plugin-customurlscheme": "^5.0.0",
    "cordova-plugin-printer": "^0.8.0",
    "cordova-plugin-safariviewcontroller": "^1.6.0",
 "@ionic/react": "^4.11.8",
"@ionic-native/safari-view-controller": "^5.20.0",

**Comment by Michael561030** [comment]
Yes, I have the same issue. How can I fix it? Help me....

**Comment by Widcket** [comment]
Hi @victororlyk, are you using Capacitor or Cordova?

**Comment by victororlyk** [comment]
@Widcket my core is capacitor,but as is is said in docs I can and I actually do use Cordova plugins.
One issue with this I can’t run
* cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME=mycoolapp*
So this I have done with manual set up

**Comment by Widcket** [comment]
@victororlyk according to [Capacitor docs](https://capacitor.ionicframework.com/docs/cordova/using-cordova-plugins/#installing-cordova-plugins) you can use the following to install cordova plugins:

```sh
npm install cordova-plugin-name
npx cap sync
```

Does that work for you?

**Comment by victororlyk** [comment]
Yes, basically printer from Cordova and this one actually half works. 
Because as was said in comments above the auth0 app says that I have been successfully logined, and logout works fine if I change my app to start not from auth page

**Comment by Widcket** [comment]
@victororlyk I managed to get it working. There's no need for the `cordova-plugin-customurlscheme` plugin, as Capacitor supports that functionality out of the box.

```typescript
// App

import React, { useEffect, useState } from 'react';

const AUTH_CONFIG = {
  clientID: '...',
  clientId: '...',
  domain: '..',
  packageIdentifier: '...'
};

const Auth0Cordova = require('@auth0/cordova');
const Client = new Auth0Cordova(AUTH_CONFIG);

const Root: React.FC = () => {
  const [logged, setLogged] = useState(false);
  const login = () => {
    const options = {
      domain: AUTH_CONFIG.domain,
      clientId: AUTH_CONFIG.clientId,
      scope: 'openid profile offline_access',
      responseType: 'token id_token',
    };

    Client.authorize(options, async (err: any, authResult: any) => {
      if (err) {
        console.log(err, 'err');
      }
      setLogged(true)
    });
  };

  useEffect(() => {
    if (!logged) {
      login();
    }
  }, []);

  return null;
};

export default Root;
```

```typescript
// Index

import { Plugins } from '@capacitor/core';
import React from 'react';
import ReactDOM from 'react-dom';
import Root from './Root';
import * as serviceWorker from './serviceWorker';

const { App, SplashScreen } = Plugins;
const Auth0Cordova = require('@auth0/cordova');

App.addListener('appUrlOpen', (data: any) => {
    Auth0Cordova.onRedirectUri(data.url);
});

SplashScreen.hide();
ReactDOM.render(<Root />, document.getElementById('root'));
serviceWorker.unregister();
```
Also don't forget to enable support for Custom URL Schemes in your iOS project's `Info.plist`:

```xml
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>None</string>
        <key>CFBundleURLName</key>
        <string>auth0</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
        </array>
    </dict>
</array>
```

**Comment by victororlyk** [comment]
@Widcket you are simply the best!!!! This should be in documentation!!!! Because I think plenty people crushed their heads onto the wall with this problem.

**Comment by 814k31** [comment]
@Widcket absolute legend thanks!

**Comment by bbjoern** [comment]
@Widcket MADE MY DAY !!!
