### ISSUE TITLE
Sign in with Apple - error on callback

### ISSUE THREAD

**Issue by yinzara** [auth0/auth0-cordova#134]
I can reproduce this consistently using the following steps using the Sample Cordova app on iOS however I have found many other combinations of steps that can reproduce the issue, just not consistently.  It happens both in the simulator and in the physical iPhone device however it is inconsistent in the simulator but always happens on the physical device using these steps.  It's happening in our production application right now and has been reported by multiple users.

You will need an Auth0 tenant that is properly configured as per the example and that has the Apple Sign in connection enabled and properly configured. You should checkout the Sample Cordova application from https://github.com/auth0-samples/auth0-cordova-samples and configure it for your Apple identifier and Auth0 tenant.

Your tenant should be configured with the Universal Login Experience using the "Classic" setup (that uses Auth0 Lock.js).

Run `npm install`, `npm build` and `cordova run` (btw I think this project could be simplified if it just added the `cordova-plugin-webpack` plugin as the build step would become part of the `cordova build`).

When the app is launched, click log in button and click Sign in with Apple.  If you are on a real Apple device touch "Use Different Apple ID" On the simulator, if you are not signed in to an Apple account, you can just continue or touch "Use Different Apple ID".

Enter a valid Apple ID and password.  If necessary, complete multi factor auth.   You will then be asked 'Do you want to continue using <app name> with your Apple ID "<apple id>"'. Touch "Continue".  If prompted to save the password, touch "Not now". 

The save password box disappears but you are returned to the prompt asking you to continue.  If you touch continue, you receive the "Oop!" Auth0 error page and are unable to continue.  

If you force kill the application, launch it again and then click the log in button, the panel is directed to auth0 and then immediately returned back to the sample app as successful (i.e. because there was an existing valid SSO session).

The Auth0 logs will show a "Successful Login" for the "apple" connection and a "Failed login" with the following error for the N/A application and connection:
```json
"error": {
    "message": "You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn't find your session. Try logging in again from the application and if the problem persists please contact the administrator.",
    "oauthError": "invalid_request",
    "type": "request-error"
  }
```

Using the `remotedebug_ios_webkit_adapter` I was able to attach my Chrome debugger to the Safari View Controller that gets launched by the auth0-cordova library. When I click continue, I see the Chrome Developer tools shows another debug session I can attach to that has the web address of my auth0 domain but by the time I attach to it, it's finished navigating and I get no information.  It appears to me that when you click Continue, an iframe or something is opening to handle the callback instead of the primary panel from the Safari View Controller.    That's why we're seeing a successful login (and a valid SSO session) but the user is not being redirected.

I'm terrified this is actually a bug in the SafariViewController with Apple Sign in and will have to be solved by Apple, but I wanted to bring it up here first.

I have attached images detailed the process.
![IMG_0015](https://user-images.githubusercontent.com/671855/81992362-272e5f80-95f8-11ea-9e5c-f88b0727eaa7.PNG)
![IMG_0016](https://user-images.githubusercontent.com/671855/81992370-2990b980-95f8-11ea-8b03-48b492f466cf.PNG)
![IMG_0017](https://user-images.githubusercontent.com/671855/81992381-2e556d80-95f8-11ea-8cfd-37fb592d979f.PNG)
![IMG_0018](https://user-images.githubusercontent.com/671855/81992383-31e8f480-95f8-11ea-865f-71089711528e.PNG)
![IMG_0019](https://user-images.githubusercontent.com/671855/81992391-34e3e500-95f8-11ea-9195-40a5928aacb9.PNG)

**Comment by n-sviridenko** [comment]
We're having the same issue (happens only 1 time on every device, the first time):

- iOS 13.0
- iPhone 8

```json
    "expo": "^36.0.0",
    "expo-asset-utils": "^1.2.0",
    "expo-av": "~8.1.0",
    "expo-blur": "~8.0.0",
    "expo-camera": "~8.0.0",
    "expo-constants": "8.0.0",
    "expo-crypto": "~8.1.0",
    "expo-file-system": "~8.0.0",
    "expo-image-picker": "~8.0.1",
    "expo-localization": "^8.1.0",
    "expo-permissions": "8.0.0",
    "expo-random": "~8.0.0",
    "expo-sharing": "^8.1.0",
    "expo-web-browser": "~8.2.1",
    "expokit": "36.1.0-rc.0",
```

```js
import axios from 'axios';
import { AuthSession } from 'expo';
import * as Random from 'expo-random';
import * as Crypto from 'expo-crypto';
import qs from 'qs';
import config from '../config';

function base64URLEncode(str) {
  return Buffer.from(str).toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
}

// `connection` is `apple`, when `connection` is `facebook` everything works
export default async function getTokenThroughFacebook(connection) {
  const redirectUrl = AuthSession.getRedirectUrl();
  const verifier = base64URLEncode(await Random.getRandomBytesAsync(32));
  const challenge = (await Crypto.digestStringAsync('SHA-256', verifier, { encoding: 'base64' }))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
  const { auth0: { baseUrl }, common: { clientId } } = config;
  const result = await AuthSession.startAsync({
    authUrl: `${config.auth0.baseUrl}authorize/`
      + `?response_type=code&scope=${encodeURIComponent('openid profile')}`
      + `&client_id=${clientId}&connection=${connection}`
      + `&code_challenge=${encodeURIComponent(challenge)}&code_challenge_method=S256`
      + `&redirect_uri=${encodeURIComponent(redirectUrl)}`,
  });
  const isSuccess = result.type === 'success' && result.params && result.params.code;
  if (!isSuccess) {
    return new Error(result.errorCode);
  }
  const {
    data: { access_token: accessToken, refresh_token: refreshToken, id_token: idToken },
  } = await axios({
    method: 'post',
    url: `${baseUrl}oauth/token`,
    data: qs.stringify({
      grant_type: 'authorization_code',
      client_id: clientId,
      code_verifier: verifier,
      code: result.params.code,
      redirect_uri: redirectUrl,
    }),
    headers: { 'content-type': 'application/x-www-form-urlencoded' },
  });
  return { accessToken, refreshToken, idToken };
}
```

**Comment by saltukalakus** [comment]
We had a call with @n-sviridenko . With the following phone, it worked for me from the first login.

* iOS 13.4.1
* iPhone 7 Plus

So, perhaps the issue is dependent on the software version and/or model. I have used the touch ID to authenticate, afaik Model 8 doesn't support it.

**Comment by n-sviridenko** [comment]
@saltukalakus model 8 supports it

**Comment by yinzara** [comment]
I actually didn't use biometrics sign in with any of the examples where I could reproduce this however I do suspect this issue may be OS specific.  The iPhone I tried this with was an iPhone XS Max.

**Comment by Widcket** [comment]
Hi @yinzara, thanks for the report. Which iOS versions have you reproduced this on?

**Comment by Widcket** [comment]
I tried to reproduce it on iOS **11.4** and **13.4.1** simulators but was unsuccessful.

**11.4**
![11 4](https://user-images.githubusercontent.com/5055789/82332230-83f49600-99bb-11ea-9131-1ab378944965.gif)

**13.4.1**
![13 4 1](https://user-images.githubusercontent.com/5055789/82332260-8c4cd100-99bb-11ea-90b8-87d530a1003c.gif)

@n-sviridenko you're not using the SDK at all, right?

**Comment by n-sviridenko** [comment]
right, I don't use SDKs, the is a code above handing authentication, you
can check it out

**Comment by yinzara** [comment]
I am running 13.4.1 and I can make this happen on both the simulator and on an iPhone device.  Have you tried uninstalling the app completely and reinstalling it before you test?

**Comment by yinzara** [comment]
I can say we're having this nearly constantly reported by testers. Every one of them is encountering this bug at least once on multiple devices.  Really frustrating. I wish I knew more.

**Comment by yinzara** [comment]
OK I think I know why you can't reproduce it. On a regular iPhone simulator that's fresh, it seems to not happen. I have to first sign in to the iPhone in settings using one account then when I try to log in via the Cordova Example click "Use a different account" and log in using that account. When you click "Continue", the error occurs.

**Comment by yinzara** [comment]
I think the example app should also support logging out.  Right now after I'm logged in, it just shows the same Log in button.  There are multiple scenarios I can't test because of that.

**Comment by Widcket** [comment]
The tests were performed on clean reset simulators. Can you please share a video of the issue?

**Comment by yinzara** [comment]
The screenshots above are from a device as I've described.  Making a video requires me to strip persona information as I don't have throw away Apple IDs. 

Can you attempt to reproduce on a simulator that is signed in?  As nearly 100% of devices in the real world are signed in to an Apple account, I feel like your tests aren't really testing the most common use case.

**Comment by yinzara** [comment]
I have Followed you on Twitter and sent you a FB message so I can send you the screencast securely.

**Comment by Widcket** [comment]
Just tested it with two Apple IDs (one in the simulator settings, the other in the app), couldn't reproduce it either. Used an iPhone 11 simulator running iOS 13.4.1.

![13 4 1-2](https://user-images.githubusercontent.com/5055789/82368228-748d4100-99eb-11ea-8d75-a469b6d6787b.gif)

**Comment by yinzara** [comment]
It looks like you're using the new login experience (not the classic one using Lock).  Could you try using the classic experience?  I can't see how that could be the difference but it might be.

**Comment by yinzara** [comment]
![ezgif-3-88d68eaebd0c](https://user-images.githubusercontent.com/671855/82389434-05b2e680-99f1-11ea-9901-35a44b2e349b.gif)

**Comment by yinzara** [comment]
![ezgif-3-86e248d650fe](https://user-images.githubusercontent.com/671855/82391923-72c97a80-99f7-11ea-84cf-aaa0263aaff5.gif)

**Comment by Widcket** [comment]
I tried with Classic Lock and wasn't able to reproduce it. May have to do with some config issue on your tenant, are you using Rules?
![ClassicLock](https://user-images.githubusercontent.com/5055789/82504023-c8258a80-9ad0-11ea-9b81-125dc34075e9.gif)

**Comment by yinzara** [comment]
I am using extensive rules, but the logs show there is a successful login.  I don't know how else to help you in reproducing this.  Do you have a physical iPhone with the latest OS?

**Comment by Widcket** [comment]
I jus tried on an iPhone 11 Pro with Classic Lock, and got the same result:

![RPReplay_Final1591138616](https://user-images.githubusercontent.com/5055789/83592928-e4deab00-a531-11ea-8d49-90a9b19844d3.gif)

It could be a configuration issue created by a Rule. You could try disabling them to see if you still get the error message.

**Comment by yinzara** [comment]
That's the problem though. There IS no error message. The error message only occurs after I push the button a second time (in which I see Auth0 error logs).  

According to Auth0's logs, my login to Apple WAS successful.  (I have logs that show the login was correct) and if I close my tab and reopen it, I've got an SSO sesssion with Auth0 and am immediately logged in. 

Logically this could not involve issues with rules if that is true as rules would have to have completed with no error to have a valid SSO session.

I don't know what else to tell you.

**Comment by cocojoe** [comment]
Hi @yinzara thanks for your comments. @Widcket has tested this Library and sample multiple times and is unable to reproduce. This would lead me to believe the issue is more likely to be in your configuration. In particular, you mention **extensive use of rules**. 

I see @Widcket has asked you to disable all rules and re-test although I can't see any confirmation you have followed this test step.

I would suggest you re-open your Auth0 support case for further investigation around your configuration. We can't reproduce the issue following the steps you provided.
