### ISSUE TITLE
Use ASWebAuthenticationSessionManager with cordova 

### ISSUE THREAD

**Issue by routingsystems** [auth0/auth0-cordova#149]
Is it Possible to use [ASWebAuthenticationSessionManager](https://github.com/jwelker110/cordova-plugin-ios-aswebauthenticationsession-api#readme)  for cordova  instead of  `cordova-plugin-safariviewcontroller ` and `cordova-plugin-customurlscheme`. 

For some Line social connection, The actual connection flow cannot be done. It’s launched the installed native application that opens safari. After authorized the connection, it’s redirect to the callback URL on safari but not to my cordova app webview. As the Auth0's session cookie is not shared with Safari browser, I got an error.

![Image from iOS (1)](https://user-images.githubusercontent.com/12960140/100170422-fd3fe900-2f08-11eb-9cda-c8475775f7ea.gif)

**Comment by Widcket** [comment]
Hi @routingsystems, in the Auth0 error screen there should be -if you scroll down- a button that shows more information about the error. Can you please share that information, redacting any sensitive data?

**Comment by routingsystems** [comment]
> Hi @routingsystems, in the Auth0 error screen there should be -if you scroll down- a button that shows more information about the error. Can you please share that information, redacting any sensitive data?

@Widcket sorry the late reply.  I cannot share that information for the moment but in my case,  It looks like Line is using a "Universal Link" to redirect to their app from the login screen. But when the app redirects to Safari it goes to Safari proper and not a webview. As cookie / session are not sharing between Safari and webview, I got an unthaurized error. 

So If I could use ASWebAuthenticationSessionManager, This would start the authentication process in "real" Safari (instead of SFSafariViewController) and then when Line finally relinquishes control the redirect should also go through "real" Safari and the authentication would complete.

**Comment by Widcket** [comment]
@routingsystems Can you please share a barebones sample app that reproduces the issue?
