### ISSUE TITLE
Could not load module crypto

### ISSUE THREAD

**Issue by siauderman** [auth0/auth0-cordova#198]
Hi, received this error in webpack:
```
Module not found: Can't resolve imported dependency "crypto"
Did you forget to install it? You can run: npm install --save crypto
```

**Comment by musznik** [comment]
same. bump.

**Comment by stevehobbsdev** [comment]
Are you using Webpack 5? If so, `crypto` will need to be polyfilled as these polyfills used to be included by Webpack 4, which is what is used to build this library - so we assume `crypto` is available.

[Webpack 5 Polyfill upgrade cheatsheet](https://gist.github.com/ef4/d2cf5672a93cf241fd47c020b9b3066a).

**Comment by siauderman** [comment]
I am using Vite. Never mind, I figured it out on my own which also results in having to use "readable-stream": "npm:vite-compatible-readable-stream@^3.6.0".

If anyone needs help, PM me.
