### ISSUE TITLE
Incorrect Instructions 

### ISSUE THREAD

**Issue by mehreencs87** [auth0/auth0-cordova#20]
Incorrect Instructions On Phonegap seed project  readme.md 

![incorrect instructions](https://cloud.githubusercontent.com/assets/14890513/13747558/aa209004-ea1a-11e5-9d8f-d4e828efe86e.png)

**Comment by dobesv** [comment]
What would the correct instructions be?

**Comment by hzalaz** [comment]
Closing this one since the issue is no longer valid since the library was rebuilt from scratch
