### ISSUE TITLE
Login with Google is not asking the account to use

### ISSUE THREAD

**Issue by fdelavega** [auth0/auth0-cordova#208]
### Describe the problem

Recently, in some new devices, when I try to login with Google it is not showing anymore the google page for choosing the Google account. Instead, it just selects the last google account used in the phone browser and tries to login with it, making imposible to select the account if you have multiple. 

If loging out the Google accounts using the phone browser, then the google login page is displayed in the app, but requiring to manually write the email and the password, so it is quite anoying for the users used to just select the account without providing the password.

The interesting point is that it does not happen in all devices.

### What was the expected behavior?

The browser should be displayed, showing the Google page for choosing what google account to use between the logged ones.

![Screenshot_2022-04-01-13-46-31-348_com android chrome](https://user-images.githubusercontent.com/2911173/161257822-be134962-d6a1-4233-bb60-c888ef87e671.jpg)

### Reproduction

Triggering the login with google,  Not happening in all devices.

It is working well in  a Xiaomi Mi A1 and a Redmi Note 9 Pro, and failing in Samsung SM-G986U

### Environment

- Using version 0.4.4
- Capacitor with Ionic 5

**Comment by stevehobbsdev** [comment]
@fdelavega Would you say this is more of an issue with Google login flow as opposed to this SDK?

I'm not sure how Google determines whether or not to show the account selector (presumably it's based on any authentication session you currently have) but I'm not sure we have any control over whether it does or doesn't. Especially problematic seeing that there is differing behaviour across different SDKs.

**Comment by stevehobbsdev** [comment]
Closing for now as I don't believe this is an SDK issue.
