### ISSUE TITLE
SafariViewController Closes before user can save or update password 

### ISSUE THREAD

**Issue by newlegendmedia** [auth0/auth0-cordova#242]
After creating a new password or logging in with a modified password, Safari prompts to save or update the saved password. The Auth0 redirect navigates away before the use can respond. 

### What was the expected behavior?
Pause to allow user to respond to the Safari prompt.

### Reproduction

- Step 1..
- Step 2..
- ...

### Environment

- **Version of this library used:**
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by Widcket** [comment]
Hi @newlegendmedia, thanks for raising this.

I'm afraid this is a known `SFSafariViewController` and `ASWebAuthenticationSession` issue, which is outside of the control of the SDK. See https://community.auth0.com/t/browser-closing-too-quickly-and-cant-save-password-when-logging-into-mobile-application/101498

I'll go ahead and close this for now, please feel free to reach out if you'd prefer to reopen.
