### ISSUE TITLE
Auth0Cordova does not exist

### ISSUE THREAD

**Issue by gregor-srdic** [auth0/auth0-cordova#30]
I have built the repository, and importing index.js from into my application, I can get access to PKCEClient not Auth0Cordova. Some documentation on that would be very useful. I managed to open the Lock widget, but now I can't find a replacement for the Auth0Cordova.onRedirectUri that would handle the passed back result.
What is more, the auth0 popup remains open in the background on my android device, any way to close that?

**Comment by darkyen** [comment]
Can you share the whole code you are using?

**Comment by gregor-srdic** [comment]
Thanks for the reply, if you look at the https://raw.githubusercontent.com/auth0/auth0-cordova/v0.1.0/dist/index.js you can see that there is no Auth0Cordova export - I guess it has been renamed to PKCEClient and documentation has not yet been updated?
Another thing, in documentation it says "cordova plugin add cordova-plugin-inappbrowser" can I replace that with cordova-plugin-safariviewcontroller, should it still work the same?

**Comment by shri-aithal** [comment]
@gregor-srdic Do you have a working sample? I too am using this in Ionic 1 and had the same issue as you (Auth0Cordova not found). I was able to get it to work by doing the change you suggested, but the callback of the authorize function isn't getting called. 

I've confirmed that window.handleOpenURL gets called, but there seems to be an issue in onRedirectUri.

**Comment by bujardeari** [comment]
Is this still the case @gregor-srdic  ?
