### ISSUE TITLE
Can this be used for Ionic2 ?

### ISSUE THREAD

**Issue by bujardeari** [auth0/auth0-cordova#32]
I am trying to use it with Ionic2 but on pc i get Cannot read property 'isAvailable' of undefined, while on android i get a strange callback url which of course is not in the list of allowed callback url-s of my auth0 Client

**Comment by darkyen** [comment]
You'll need to installs the plugins as listed in the readme and this works for ionic 2.

**Comment by gregor-srdic** [comment]
We are using this for the ionic project (v1 actually, but in v2 it would be the same), that is both a web and mobile application (ios and android). This library is used for native applications, while for the web we use auth0.js client alone.

You have to add this "strange" url to the list of allowed callback urls, and when you install the plugins, Android/iOs will know to redirect the callback back to your app.

Not sure if you are aware, there is actually an example done with Ionic v2 in this repo https://github.com/auth0/auth0-cordova/tree/master/example/ionic

**Comment by bujardeari** [comment]
Thank you both! 
Yes i am aware of the Ionic example in this repo but i was confused which readme to use, the one on the root page of the repo or the one at the ionic example. Gregor if you use this pluggins, how do you work in dev mode if this is not working when testing in the computer browser? Or is it only on Chrome it doesnt work?

**Comment by gregor-srdic** [comment]
Plugins only run on cordova platforms (native builds), none of the desktop browsers will have access to them. (There is a platform "browser" in ionic, but I don't think that will be useful in your case.)

To test your "login code" on the device, you have to connect your device to the development machine and run "ionic run android/ios" command.  You can also use simulator/emulator on both platforms.

For testing other features (that require login) you can store the access token in local storage on mobile and copy it to your chrome browser. Authentication flow usually first checks for the stored token and if available, user is immediately authenticated.
Or you can develop a separate authorisation flow if the app is running in a desktop browser - if you intend to put it on web also - we do it this way.
