### ISSUE TITLE
issues with testing it on the new ionic 2 example

### ISSUE THREAD

**Issue by biemond** [auth0/auth0-cordova#36]
hi,

I was testing the new ionic 2 example https://github.com/auth0-samples/auth0-ionic2-samples and it works on android and ios with the google authentication.

But when I logout and do a login again it will open a window again on IOS but in this case the url is empty and can only press done.
Do the same on android it closes everything and need to open the app again without being authenticated.
I only get it working with android or IOS emulate when I wipe all the data.

When you look at the provider code, it is not much I can do.
https://github.com/auth0-samples/auth0-ionic2-samples/blob/master/01-Login/src/services/auth.service.ts#L55

Is this is auth0-cordova issue and do I need to cleanup something when I do logout.

thanks Edwin and keep up the great work.

**Comment by gregor-srdic** [comment]
this is the same issue as [Issue 31](https://github.com/auth0/auth0-cordova/issues/31), I was also unable to find a solution yet :(

**Comment by gregor-srdic** [comment]
try adding timeout in window.handleOpenURL function, worked for me (then close the issue :))
```
window.handleOpenURL = function (url) { 
window.setTimeout(function () {
PKCEClient.onRedirectUri(url); 
}, 100);
}
```

**Comment by biemond** [comment]
Nice this works for me on the ionic 2 example

```
      (<any>window).handleOpenURL = (url) => {
        (<any>window).setTimeout(function () {
          Auth0Cordova.onRedirectUri(url);
        }, 100);
      };
```

**Comment by cyberabis** [comment]
@biemond timeout still doesn't help me. After auth0 login, the app crashes and restarts in Android. Whereas in iOS I get a white screen until I close and reopen the app.

**Comment by biemond** [comment]
it works for me on android and ios . are you also using the ionic 2 example?

**Comment by cyberabis** [comment]
Yes tried with that, can you share your package.json? I suspect it's some issue with the versions we have. Here's mine:
`
"dependencies": {
        "@angular/common": "4.1.0",
        "@angular/compiler": "4.1.0",
        "@angular/compiler-cli": "4.1.0",
        "@angular/core": "4.1.0",
        "@angular/forms": "4.1.0",
        "@angular/http": "4.1.0",
        "@angular/platform-browser": "4.1.0",
        "@angular/platform-browser-dynamic": "4.1.0",
        "@auth0/cordova": "^0.1.0",
        "@ionic-native/core": "3.6.1",
        "@ionic-native/network": "^3.10.3",
        "@ionic-native/splash-screen": "3.6.1",
        "@ionic-native/status-bar": "3.6.1",
        "@ionic/storage": "2.0.1",
        "angular2-jwt": "0.2.3",
        "auth0-js": "8.6.1",
        "cordova-android": "^6.2.3",
        "cordova-ios": "^4.4.0",
        "cordova-plugin-console": "1.0.5",
        "cordova-plugin-customurlscheme": "4.2.0",
        "cordova-plugin-device": "1.1.4",
        "cordova-plugin-network-information": "^1.3.3",
        "cordova-plugin-safariviewcontroller": "1.4.6",
        "cordova-plugin-splashscreen": "4.0.3",
        "cordova-plugin-statusbar": "2.2.3",
        "cordova-plugin-whitelist": "1.3.1",
        "cordova-sqlite-storage": "^2.0.4",
        "ionic-angular": "3.2.1",
        "ionic-plugin-keyboard": "2.2.1",
        "ionicons": "3.0.0",
        "moment": "^2.18.1",
        "rxjs": "5.1.1",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.10"
    },
    "devDependencies": {
        "@ionic/app-scripts": "1.3.7",
        "@ionic/cli-plugin-cordova": "1.1.2",
        "@ionic/cli-plugin-ionic-angular": "1.1.2",
        "typescript": "2.2.1"
    }
`

**Comment by biemond** [comment]
```
  "dependencies": {
    "@angular/common": "4.1.2",
    "@angular/compiler": "4.1.2",
    "@angular/compiler-cli": "4.1.2",
    "@angular/core": "4.1.2",
    "@angular/forms": "4.1.2",
    "@angular/http": "4.1.2",
    "@angular/platform-browser": "4.1.2",
    "@angular/platform-browser-dynamic": "4.1.2",
    "@ionic-native/core": "3.6.1",
    "@ionic-native/splash-screen": "3.6.1",
    "@ionic-native/status-bar": "3.6.1",
    "@ionic/storage": "2.0.1",
    "ionic-angular": "3.3.0",
    "ionicons": "3.0.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.10",
    "@auth0/cordova": "^0.1.0",
    "@ionic-native/youtube-video-player": "^3.10.2",
    "@ionic/cloud-angular": "^0.12.0",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "angular2-google-maps": "0.17.0",
    "angular2-jwt": "0.2.3",
    "auth0-js": "^8.6.1",
    "cordova-android": "^6.2.3",
    "cordova-ios": "~4.4.0",
    "cordova-plugin-android-native-pdfviewer": "^1.2.0",
    "cordova-plugin-compat": "~1.1.0",
    "cordova-plugin-console": "~1.0.5",
    "cordova-plugin-customurlscheme": "^4.2.0",
    "cordova-plugin-device": "~1.1.3",
    "cordova-plugin-file": "~4.3.0",
    "cordova-plugin-google-analytics": "~1.7.11",
    "cordova-plugin-googlemaps": "~1.4.0",
    "cordova-plugin-inappbrowser": "~1.7.1",
    "cordova-plugin-safariviewcontroller": "^1.4.7",
    "cordova-plugin-splashscreen": "~4.0.1",
    "cordova-plugin-statusbar": "~2.2.1",
    "cordova-plugin-whitelist": "~1.3.1",
    "cordova-sqlite-storage": "~2.0.2",
    "es6-shim": "0.35.1",
    "ionic": "3.1.2",
    "ionic-plugin-keyboard": "~2.2.1",
    "ngx-pagination": "^3.0.0",
    "nl.kingsquare.cordova.background-audio": "~1.0.1",
    "phonegap-plugin-push": "~1.10.2"
  },
```

**Comment by cyberabis** [comment]
Thanks @biemond, tried your versions, but still no luck. I am downgrading to ionic 2 and checking out. Will post back in this thread if I find the issue!

**Comment by biemond** [comment]
for me its was already working with the demo ionic app and ionic 3 with lazy loading. 

did you install these plugins + plus do the auth0 side
```
     "cordova-plugin-safariviewcontroller": {},
      "cordova-plugin-customurlscheme": {
        "URL_SCHEME": "YOUR_PACKAGE",
        "ANDROID_SCHEME": "YOUR_PACKAGE",
        "ANDROID_HOST": "xxxx.eu.auth0.com",
        "ANDROID_PATHPREFIX": "/cordova/YOUR_PACKAGE/callback"
      },
      "cordova-plugin-inappbrowser": {},
```

and
```
    <feature name="InAppBrowser">
        <param name="ios-package" value="CDVInAppBrowser" />
        <param name="android-package" value="org.apache.cordova.inappbrowser.InAppBrowser" />
    </feature>
    <engine name="android" spec="^6.2.3" />
    <engine name="ios" spec="~4.4.0" />
```

**Comment by cyberabis** [comment]
The InAppBrowser was missing but even after including that the app is crashing, probably it's an issue specific to my configuration or so. Giving up for now :(
Again, thanks for checking this!

**Comment by bujardeari** [comment]
gregor-srdic i have the same issue on android , how did you fix it on android?

**Comment by nathantaal** [comment]
So this is the same problem I'm having right now?
When pressing login getting, redirect reopens the app instead of loggin in?

**Comment by niren777** [comment]
I'm facing similar issue with android cordova app. When I click on login button the Auth0Corodova function opens OS browser. Once the OS browser opens our app is closed/crashed. There is no log why is it crashing. Sometime app crashes/closes immediately after OS browser open, sometime app crashes/closes after 5-10 secs. sometime app crashes/closes when authentication finished. Is there any solution?

I'm using 
Android version 5.0.2
@auth0/cordova 0.3.0
cordova-plugin-customurlscheme 4.3.0 (tried 4.2.0)
cordova-plugin-safariviewcontroller 1.4.7 (tried 1.5.3)
