### ISSUE TITLE
Ionic v2 iOS: Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by saschwarz** [auth0/auth0-cordova#38]
I'm assuming this is due to something with the custom urlscheme configuration?

I'm using the Ionic example and I've edited `package.json` as follows to match my widget id:

```
            "cordova-plugin-customurlscheme": {
                "URL_SCHEME": "com.agilitycoursemaster.ACMaster"
            },
```

Which generates this entry in config.xml:

```
    <plugin name="cordova-plugin-customurlscheme" spec="^4.2.0">
        <variable name="URL_SCHEME" value="com.agilitycoursemaster.ACMaster" />
    </plugin>
```

Which matches the name of my callback URL in Auth0:
`com.agilitycoursemaster.ACMaster://agilitycoursemaster.auth0.com/cordova/com.agilitycoursemaster.ACMaster/callback`

I've confirmed the login succeeds via the Auth0 logs.

I couldn't find any documentation on setting this up correctly.

**Comment by gregor-srdic** [comment]
What type of login are you using, social or database?
If social, have you tried to clear Safari web site data in the iOs settings, and then to login again?

**Comment by saschwarz** [comment]
Thanks, but I've tried both and cleared Safari web site data in the settings before each attempt and it's still the same error.

**Comment by saschwarz** [comment]
Thanks! I'd love to understand what makes a plugin need to be removed/reinstalled...

Now my console.log in the intent handler is being called but the Auth0 screen stays up with the busy spinner. If I click the Done button on the browser window I get the user canceled alert.

I also tried the "nuclear option" and removed/added the ios platform.

**Comment by saschwarz** [comment]
Found the solution! The customurlscheme and the pieces Auth0 uses to create it must all be lower case:

package.json:

            "cordova-plugin-customurlscheme": {
                "URL_SCHEME": "com.agilitycoursemaster.acmaster",
                "ANDROID_SCHEME": " ",
                "ANDROID_HOST": " ",
                "ANDROID_PATHPREFIX": "/"
            }

auth0-variables.ts:

    export class Auth0Vars {
        static AUTH0_CLIENT_ID = 'xxxxxxxxxxxxxxxxx';
        static AUTH0_DOMAIN = 'agilitycoursemaster.auth0.com';
        static PACKAGE_IDENTIFIER = 'com.agilitycoursemaster.acmaster';
    }

@gregor-srdic thanks for your help!
