### ISSUE TITLE
Configuration used with auth0-lock doesn't appear to be compatible

### ISSUE THREAD

**Issue by bradrust** [auth0/auth0-cordova#39]
We customize our auth0-lock instance with a custom dictionary, icons, colors, etc...  I am passing in the same config to Auth0.Cordova but those customizations don't appear to be honored.   The title of the lock dialog presented is the name of the auth0 client (which I consider somewhat internal)

Is this expected or just not implemented yet?

**Comment by saschwarz** [comment]
AFAIK auth.js ends up invoking the hosted lock login dialog. I was able to insert all my static customization into the Auth0 dashboard under "Hosted Pages".

The only problem I've found is I can't figure out how to pass dynamic data into the `config.extraParams` read by lock without getting a warning about unknown parameters in my client's console. Specifically, I want to pass along `initialScreen` which gets encoded as `initial_screen` by auth.js and then auth.js complains about it.

**Comment by hzalaz** [comment]
@bradrust its expected since this is not lock but a call to render your tenant hosted login page.
@saschwarz its just a warning so it will still work and we won't block it in the library

**Comment by simonwatt** [comment]
@saschwarz Did you end up managing to set initialScreen dynamically? I understand I can change it on the lock configuration on the dashboard hosted page, however I want to change it depending on an initial action my user takes, but I'm not sure what option parameter or config option to pass to auth0-cordova.

**Comment by saschwarz** [comment]
In JS when you call `authorize`:

            const options = {
                initialScreen: this.signedUp ? 'login' : 'signUp',
                ...
            };
            this.client.authorize(options, yourCallback);

Then on the Hosted Pages page on Auth0 for the login page add a check:

    ...
    var lock = new Auth0Lock(config.clientID, config.auth0Domain, {
      auth: {
        redirectUrl: config.callbackURL,
        responseType: config.callbackOnLocationHash ? 'token' : 'code',
        params: config.internalOptions
      },
      assetsUrl:  config.assetsUrl,
      allowedConnections: connection ? [connection] : null,
      rememberLastLogin: !prompt,
      language: language,
      // any camelCase options you supply are converted to lowercase underscore and put in extraParams:
      initialScreen: config.extraParams.initial_screen || 'login',
      ...

It took me a while to reverse engineer how it works.

**Comment by simonwatt** [comment]
@saschwarz Awesome, that worked perfectly and no doubt saved me a lot of time as I couldn't see anything in the documentation. Thanks!
