### ISSUE TITLE
Cannot read property 'isAvailable' of undefined

### ISSUE THREAD

**Issue by ansien12** [auth0/auth0-cordova#41]
![image](https://cloud.githubusercontent.com/assets/1700132/26534717/5f4bc82e-4427-11e7-844b-8c345378f057.png)

Running cordova example on Phonegap desktop. Any ideas on how to fix this?

**Comment by gregor-srdic** [comment]
I believe this is due to missing "cordova-plugin-safariviewcontroller" plugin, I am not sure if it is available for desktop. For desktop web browser authentication, we are using auth0-js lib only - auth0WebClient.popup.authorize ...

**Comment by ansien12** [comment]
@gregor-srdic It works on desktop mode, but when i use Phonegap desktop to test it on Android/iOS it'll result in the error above.

**Comment by gregor-srdic** [comment]
I am not well familiar, Phonegap desktop is online build tool? Then is it possible, it does not have the plugin available?

**Comment by ansien12** [comment]
No it doesn't build it. I think that's why the plugin isn't working. It works fine after building.

**Comment by darkyen** [comment]
Phonegap desktop uses Phonegap serve, you should be able to write a custom client for the phonegap serve's mobile application forking and adding any custom plugins needed (this is the recommended way) https://github.com/phonegap/phonegap-app-developer#adding-custom-plugins.

**Comment by joeflack4** [comment]
I'm writing a Cordova app that utilizes auth0 via Auth0Cordova.

I'm using React, so I'm using CreateReactApp to build my Cordova activation and handle development. When running my app using Webpack in the browser and trying to log in, I'm getting this error.

During my debugging session, I can see that it's erroring out here:
```javascript
function Browser() {
  this.browser = window.SafariViewController;
  this.open = this.open.bind(this);
  this.close = this.close.bind(this);
}

Browser.isAvailable = function (callback) {
  window.SafariViewController.isAvailable(callback);  <----------------
};


Browser.prototype.open = function (url, callback) {
  var options = {
    hidden: false,
    url: url
  };

  this.browser.show(options, function (result) {
    callback(null, result);
  }, function (message) {
    callback(new Error(message));
  });
};

Browser.prototype.close = function () {
  this.browser.hide();
};

module.exports = Browser;

```

@darkyen Recommends writing a custom plugin, but I don't want to do that. I just want to use auth0 in my app and be able to check that it's working fine in development without building first as suggested by @ansien12 .

Here's a gist of what I'm working with: https://gist.github.com/joeflack4/4b271a33a072ad097150374dfa304a68

**Comment by tareqdayya** [comment]
i'm having this problem with ionic/cordova. Anyone knows how to solve it?
