### ISSUE TITLE
idToken "invalid signature" JWT

### ISSUE THREAD

**Issue by zompad** [auth0/auth0-cordova#43]
When running authorize I have been trying to using the JWT idToken to sign into firebase by
firebase.auth().signInWithCustomToken(idToken)

However I getting a "bad request" error message.  So I copied out the JWT idToken string to the debugger on https://jwt.io/ and it is showing "Invalid Signature".

Please can you confirm if there is an issue with the JWT idToken.

**Comment by gregor-srdic** [comment]
I believe it shows the invalid signature because it does not have the private key to verify the signature - your token is fine if the displayed content seems OK

**Comment by darkyen** [comment]
Firebase token requires an extra step, as of now you cannot just pass firebase the token you recieve at the end of authentication / authorization. You'll need to use the /delegation endpoint as described in the Firebase tutorial to get an id_token that can be used to authenticate to firebase.
