### ISSUE TITLE
Doesn't work with Ionic 1

### ISSUE THREAD

**Issue by cloudexpresssolutions** [auth0/auth0-cordova#45]
Hi, We followed these steps for ionic 1 and it doesn't work. can you please let us know the workaround for ionic 1 asap please? We are at production and are not able to get Google to work.

The error message we get is "undefined" when we try this fix.

Please help asap - drop me a note at info@cloudexpresssolutions.com if you need more information.

**Comment by cloudexpresssolutions** [comment]
Is there any update on the issue below? Let me know if you need any further details?
We are using ionic v1, Node 4.2.2, Cordova 1

**Comment by darkyen** [comment]
I reached out to you from the support center. Can you send a har file?

**Comment by cloudexpresssolutions** [comment]
Hi Abhishek,

Can you please let me know how can I send a stack trace from the mobile
application?

*Best Regards,*

*Cloud Express Solutions Private Limited*
Direct : (91) 80 2685 2080  | Mobile : (91) 9902 503 503

**Comment by darkyen** [comment]
This is being handled in support center.

**Comment by cloudexpresssolutions** [comment]
Hi Abhisek, We tried implementing the fix you helped us for the IOS app in to an android code base. After following the instructions we ran in to some issues. Can you please help?

After installing cordova plugin add cordova-plugin-safariviewcontroller   in android app version 1 build is failing 

Please see the below stacktrace
Running: C:\Users\Cloud Express\Desktop\StreetBuzz\platforms\android\gradlew cdvBuildDebug -b C:\Users\Cloud Express\Desktop\StreetBuzz\platforms\android\build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:customtabs:23.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/customtabs/23.2.0/customtabs-23.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/customtabs/23.2.0/customtabs-23.2.0.jar
         file:/C:/Android/sdk/extras/android/m2repository/com/android/support/customtabs/23.2.0/customtabs-23.2.0.pom

BUILD FAILED
Total time: 6.486 secs

         file:/C:/Android/sdk/extras/android/m2repository/com/android/support/customtabs/23.2.0/customtabs-23.2.0.jar
         file:/C:/Android/sdk/extras/google/m2repository/com/android/support/customtabs/23.2.0/customtabs-23.2.0.pom
         file:/C:/Android/sdk/extras/google/m2repository/com/android/support/customtabs/23.2.0/customtabs-23.2.0.jar
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


C:\Users\Cloud Express\Desktop\StreetBuzz\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                    ^
Error code 1 for command: cmd with args: /s /c ""C:\Users\Cloud Express\Desktop\StreetBuzz\platforms\android\gradlew" cdvBuildDebug -b "C:\Users\Cloud Express\Desktop\StreetBuzz\platforms\android\build.gradle" -Dorg.gradle.daemon=true"

ERROR building one of the platforms: Error: cmd: Command failed with exit code 1
You may not have the required environment or OS to build this project

Error: cmd: Command failed with exit code 1

**Comment by darkyen** [comment]
That is an issue with the `cordova-plugin-safariviewcontroller` plugin. Can you please create an issue at https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller from a higher level it seems its an error with the dependency / cordova version etc.
