### ISSUE TITLE
No logout method implementation.

### ISSUE THREAD

**Issue by davidemerritt** [auth0/auth0-cordova#49]
Is there a reason it wasn't included? I've written an implementation using this repo's getAgent logic (< 10 lines) and would be happy to open a PR for this feature, if that sounds good to you @chenkie?

**Comment by darkyen** [comment]
Ideally from the applications perspective, a logout is analogous to deleting the local refresh token / cleaning out the session on the device. When using Hosted Login Page the user should then be prompted for the credentials again. You should disable sso in order to achieve this.

The `/logout` endpoint in the Auth0 tenant is a federated logout which will log you out of all the other applications / websites on this device using this tenant.

**Comment by davidemerritt** [comment]
I do need the use of the federated logout. I internally handle the session logout for the user, but need a logout of my system (session) to also trigger the federated logout within the same native webAgent. Can name the method federatedLogout, or just keep this logic within my own repo, but thought this may be useful functionality for others as it requires the same webagent view that auth0/autho-cordova uses.

**Comment by darkyen** [comment]
Makes sense, I’ll consider it internally.

**Comment by joewoodhouse** [comment]
@davidemerritt I'd be interested in how you've implemented this as I need the same functionality? If you could push that PR it would be much appreciated (even if @darkyen later rejects it). Thanks!

**Comment by jebbench** [comment]
Any update on this? We're also missing this functionality (a user can currently logout of our application but Auth0 remembers them and they're not prompted for their password when they return).

**Comment by markkopaas** [comment]
We implemented the logout, but we do not use sso right now, so it is not battle-tested. 
Here you are:
https://github.com/areo/auth0-cordova/commit/bcb1eece73735c526fdbb5b28120807f94f38484

**Comment by davidemerritt** [comment]
@jebbench - I've opened a PR if you want to use that fork, its working for me in production. https://github.com/auth0/auth0-cordova/pull/76

**Comment by davidemerritt** [comment]
@joe

**Comment by darkyen** [comment]
Just wanted to close the loop on this, I am currently refactoring / rewriting the lib to be more integrated with the Cordova Ecosystem and provide better / graceful support for Ionic. I'm looking int othe PR @davidemerritt

**Comment by davidemerritt** [comment]
@darkyen - great news, let me know if you have any questions on that other PR. thanks

**Comment by JohnMcLear** [comment]
*Gentle bump :)  It'd be great to see this land!  @darkyen

**Comment by JohnMcLear** [comment]
*Another gentle bump.  Is this already in or?? :)

**Comment by JohnMcLear** [comment]
And...  Another gentle bump..

**Comment by darkyen** [comment]
Hey John, 

At the moment we are changing a bunch of things with this SDK, in general, and I'll respond in ~2 weeks with more on the repo. Regarding the feature itself, I think I mentioned it on another issue but it seems that might have been a support ticket, ideally from an app point of view if you were to invoke federated logout which may be desirable in some conditions, the user's session will be revoked permanently on the device. This might have unintended consequences in the SSO scenario where other applications or websites might still have a session, in general, if you just want to prompt the user to log in again you can call .authorize() with `prompt=login`. That said, I definitely see how `prompt=login` will run into shortcomings where you _explicitely_ want to log the user out, at the moment you'll need to open the `SFSafariViewController` explicitly with a url for `/v2/logout` which should not be the case in the future releases. I'll follow up in ~2 weeks with a new issue regarding the future of this SDK.

**Comment by JohnMcLear** [comment]
@darkyen Very happy to wait 2 weeks :)  Thanks for the update!  You guys are doing an awesome job, I started looking at alternatives but your comment means I will just be patient instead and stick w/ Auth0 :)

**Comment by darkyen** [comment]
> @darkyen Very happy to wait 2 weeks :) Thanks for the update! You guys are doing an awesome job, I started looking at alternatives but your comment means I will just be patient instead and stick w/ Auth0 :)

We are currently investing resources internally investigating resources towards building a better SDK that covers the gaps here, at the very least provide some capabilities similar to the iOS / Android Native SDKs have. However, we will need some more time to commit to a deadline, I'd encourage you to open a support ticket if you need immediate resolution around certain features that aren't implemented. 


> @darkyen is your two weeks longer than rest of the people? I still can't find any solution to perform auth0 logout for a user. Really sucks. !!!

Sorry about the delay but we are trying to figure out what is the best strategy moving forward not just for Cordova but for hybrid stack in general. 

The simplest way to _force_ re-login (for example to force user to login again / validate access), as mentioned in past is to pass `prompt=login`, if that is not an acceptable solution, you'll need to use the underlying plugin to open the url that points to v2/logout that said, as we plan to add support for the shared system webview with SSO, this might have unintended consequences (like logging the user out of websites that rely on auth0 for a session, it will however not force multi-app logout).

One possible alternative that has been discussed is to force the session for a short-lived session, as most mobile apps will rely on a `refresh_token` instead to maintain the session, revoking that session directly in-app is much simpler.

**Comment by jayparmar** [comment]
@darkyen non of your suggested solutions (I call them hacks :()  are  not usable in production. I created a new tenant for a new app which is production ready and guess what, Auth0 is THE PROBLEM. Would have been better off with other OAuth2 solution providers. Really disappointing that Auth0 is not even allowing new tenants to disable SSO.Really poor thinking form Auth0 team

**Comment by darkyen** [comment]
> @darkyen non of your suggested solutions (I call them hacks :() are not usable in production. I created a new tenant for a new app which is production ready and guess what, Auth0 is THE PROBLEM. Would have been better off with other OAuth2 solution providers. Really disappointing that Auth0 is not even allowing new tenants to disable SSO.Really poor thinking form Auth0 team

Can you create a support ticket regarding disabling/reducing SSO?

**Comment by jayparmar** [comment]
@darkyen is this current github issue not good enough to fix the issue?

**Comment by JohnMcLear** [comment]
@jayparmar I'm sure @darkyen is working as hard as possible on getting this resolved for us, let's stop throwing stones in this issue and be patient for his fix.  I am confident Auth0 will be taking the right decisions on behalf of their community and I'm grateful to @darkyen for communicating so effectively with us.

@jayparmar as @darkyen has mentioned creating a support ticket is a great step you can take and in the mean time we can be confident that @darkyen has this on his radar and will be submitting a fix as soon as possible :)  I'm frustrated too btw but I'm mindful that a a proper fix (which encapsulates more than just a handful of open issues and provides a wealth of new fixes) is the correct approach and IMHO worth a wait.  While the proposed schedule was missed let's try to use encouraging language to promote this issue within Auth0 so Auth0 can provide the proper resources.

Thanks both for transparent conversations and your commitments to open source :)

Also @jayparmar when you open the issue bump us all here and we can be sure to create a similar issue with Auth0 to ensure a fix is poste-haste.

RE "is this current github issue not good enough to fix the issue?" -- In growing organizations they tend to have triaging and to get onto their "queue" you often need to create a support ticket and that support ticket has to come through a customer.  It's just business as usual and sadly part of modern bureaucracy ;/  No hate thrown at Auth0 here, I'm pretty sure all the companies I work w/ do the same ;)

**Comment by jayparmar** [comment]
@JohnMcLear and @darkyen why don't Auth0 then still allow to disable SSO until they have the proper solution? They do allow it for old tenants, don't they?

**Comment by darkyen** [comment]
> @JohnMcLear and @darkyen why don't Auth0 then still allow to disable SSO until they have the proper solution? They do allow it for old tenants, don't they?

I am not sure what you mean by _not allow disabling SSO_ which is why I asked you to create a support ticket as the support team will be able to handle it much better than I can. Session management is a multi-faceted topic which involves far more than enabling and disabling an SSO, consider for example what should happen if we were to disable SSO and you perform Custom MFA or any other Custom redirect using Redirect Rules, what will happen when the user comes back, what will happen if you want to access the user's information in the app your redirected to in order to perform an authenticated action. We have significantly changed the inner workings on the SSO front in recent years allowing more complex interactions to be possible. Which is why I encourage you to approach support with the need to disable SSO, over the top of my head you should be able to set a very short-lived should session which is analogous to not having a session for most use-cases.

**Comment by jayparmar** [comment]
@darkyen if you can please read the solution for this question https://community.auth0.com/t/log-out-doesnt-work-and-automatically-sign-in/14826
