### ISSUE TITLE
Cannot make OAuth request in Android older than 6.0.0

### ISSUE THREAD

**Issue by ghost** [auth0/auth0-cordova#50]
I am trying to add Auth0 JWT authentication to Ionic Cordova app. 

As i understand SafariViewController on which this plugin relies on do not work on older versions of webview, so for that reason auth0-cordova uses fallback to cordova-inappbrowser. But for now Google no longer support OAuth connection for embeeded browsers, so i get “Dissalowed user agent”. 

I can put `<preference name="OverrideUserAgent" value="Mozilla/5.0 Google" />` into my config.xml, which makes it work on some devices, but on other devices inappbrowser cannot handle custom uri scheme. So I cannot rely on that workaround. 

Would be gratefull for any kind of help.

**Comment by darkyen** [comment]
It should use Android's Custom Chrome Tabs implementation on Android, can you share your config.xml also please read the installation instructions for SafariViewController Plugin (3rd party) which should abstract android / chrome integration at https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller

**Comment by acatalina** [comment]
I am in a similar situation and the only fix I found was installing Chrome in the device... any other more permanent solution?

**Comment by JohnMcLear** [comment]
https://github.com/auth0/auth0-cordova/pull/82/files

**Comment by Widcket** [comment]
Going to close this one. Please ping if this is still an issue.
