### ISSUE TITLE
Can't authorize if using a proxy

### ISSUE THREAD

**Issue by VolodymyrTymtsiv** [auth0/auth0-cordova#55]
When I try to login to the application using [proxies](https://www.us-proxy.org/), auth0 widget doesn't fetch accounts.

`
auth0Config = {
      clientId: ...
     clientID: ...
    domain: ...
    callbackURL: location.href,
    packageIdentifier: ...
  };

let options = {
      scope: 'openid profile ',
      connection: 'google-oauth2'
    };

    new Auth0Cordova(this.auth0Config).authorize(options, (error, authResult) => {....})

![img_20171108_140825](https://user-images.githubusercontent.com/19935467/32548504-84c5dc24-c48e-11e7-9b3e-566b26abe2b5.jpg)

Without proxies, all works fine and I can log in.

![img_20171107_210107](https://user-images.githubusercontent.com/19935467/32558045-8aa6ead4-c4ac-11e7-8f45-131d3e775682.jpg)

**Comment by darkyen** [comment]
Can you share the message you get from the networking erro?

**Comment by VolodymyrTymtsiv** [comment]
That happens when using an HTTP proxy, not HTTPS.
