### ISSUE TITLE
Document requirement for safariviewcontroller

### ISSUE THREAD

**Issue by JohnMcLear** [auth0/auth0-cordova#59]
Safari View controller is pretty heavy as far as deps go.

Did you guys attempt to develop the plugin without this dep or was it a no go?

Cheers

**Comment by darkyen** [comment]
So far we do not have any plans to develop a safari-view-controller alternative, the plugin / dev dependency offers excellent integration with the browser apis

**Comment by JohnMcLear** [comment]
Absolutely, but what I am unsure of is why you need any deps at all?  Like what is it about auth0 that requires such a dependency?  Is it the callback method or?

Not trying to be critical of the project here I am just surprised that can't be handled by Cordova without such requirements.

**Comment by JohnMcLear** [comment]
Super useful info tnx!  Let's close this but keep it for posterity.  I'm +1 all things security but when it adds 10Mb to my app it feels a little like adding flash to handle clipboard (to draw an analogy).

Hopefully in the future we can see a cleaner/less heavy solution but until then I can live with how things are.
