### ISSUE TITLE
How to access user metadata?

### ISSUE THREAD

**Issue by JohnMcLear** [auth0/auth0-cordova#60]
As per the title, I'm not seeing any method in the client or any obvious way to easily set and retrieve metadata for a given app/user.

It's probably super obvious so sorry if I'm missing something that's in the docs -__-

**Comment by darkyen** [comment]
Hi John, 

What is the meta-data that you are trying to fetch? You can add metadata to the idToken which is returned by the lib as idTokenPayload alternatively, you can make a call to the /userinfo endpoint in both the cases any non standard metadata will needed to be added to the profile / idToken as described at https://auth0.com/docs/rules/current#copy-user-metadata-to-id-token

**Comment by JohnMcLear** [comment]
not /userInfo (I think), I have that working great thanks!

I am talking about the "user_metadata" value that auth0 exposes.

I'm still getting to grips with auth0 but as the admin interface states the user has write control over this value and with this in mind I'm looking for it to be an easy way for a user to store and retrieve a simple value.

I was expecting something like..

```
auth0.client.set("user_metadata", "thisData", function(){});
```
Like I said I'm a huge noob to auth0 but I don't feel like https://auth0.com/docs/rules/current#copy-user-metadata-to-id-token does this...  Happy to be proven wrong though!

**Comment by Pita** [comment]
Hello, 

I'm working with John on this project. We basicly want to store a bit of data with each user, its just a string basicly, its all the information we need to store for a user for our specific use case.

I read a bit through the API docs. I understand how we can set meta data via the management API. But I don't understand yet how to read it via the Authentication API. Ideally we could retrieve the metadata at any moment, long after the initial authentication happened. Is this possible? I looked a bit into rules and idtoken but didn't manage to wrap my head around it.

Hope that clearifies things a bit

Peter

**Comment by JohnMcLear** [comment]
We decided to workaround auth0 in this instance (somewhat) by just using the bearer and sub..

Here is the example code we used to set and get metadata...

You will need to set SUB and IDTOKEN -- these values are available in the auth0.client object.

First we SET(PATCH) the value..
```
    var url = "https://DOMAIN.auth0.com/api/v2/users/"+SUB;
    $.ajax({
      method: "PATCH",
      url: url,
      data: {
        user_metadata: {
          whatever: "somevalue"
        }
      },
      headers: {
        'authorization': "Bearer "+IDTOKEN
      },
      success: function(d){
        console.log("success", d);
      },
      error: function(e){
        console.log("error getting metadata", e)
      }
    })
```

and here we GET the value..
```
    var url = "https://DOMAIN.auth0.com/api/v2/users/"+SUB+"?fields=user_metadata";
    $.get({
      url: url,
      headers: {
        'authorization': "Bearer "+IDTOKEN
      },
      success: function(d){
        console.log("success", d)
        if(d.user_metadata){
          console.log(d.user_metadata); // should be {whatever: "somevalue"}
        }
      },
      error: function(e){
        console.log("error getting metadata", e)
      }
    })
```

**Comment by darkyen** [comment]
Hi John, This is a historically legacy feature that works for now (basically allows you to have current_user) access through the ID_Token in future you should be able to get tokens for Management API directly with the scope for current_user. I'll get back to you with the blueprint for that.

**Comment by JohnMcLear** [comment]
Thanks I'd like to make sure I'm not using something that will be deprecated in x months! :)
