### ISSUE TITLE
Callback not fired in client.authorize() when connection parameter is passed

### ISSUE THREAD

**Issue by thomasmarren** [auth0/auth0-cordova#63]
I'm trying to open Google authentication directly from my Cordova app rather than going to the hosted login page and having the user click "Sign in with Google." I'm passing the connection parameter into the `client.authorize()` function like so:

```javascript
    let auth0Config = {
      clientId: this.config.auth0.clientId,
      domain: this.config.auth0.domain,
      callbackURL: this.config.auth0.callbackURL,
      packageIdentifier: this.config.auth0.packageIdentifier
    }
    const client = new Auth0Cordova(auth0Config)
    const options = {
      scope: 'openid profile offline_access',
      audience: this.config.auth0.audience,
      connection:'google-oauth2',
    }
    client.authorize(options, (err, authResult) => {})
```

It is loading the Google OAuth page as expected however once the user authenticates, the callback is not fired. The url is being redirected back to the app, and I am passing it into `Auth0Cordova.onRedirectUri()`

The same process works as expected without the `connection` parameter so I'm wondering if this library does not support a `connection` parameter? I know this is possible with the Auth0-js library.

Thank you

EDIT: It only occurs when I've previously logged in with Google and it remembers my login. The redirect seems to be happening too early. If it is my first time authenticating with Google it works as expected.

**Comment by darkyen** [comment]
Hi Thomas, apologies for the delay, can you try the latest version? I'm trying to reproduce this atm.

**Comment by bocodigital** [comment]
I can confirm same issue using google. Call back never gets fired and no error is thrown.
