### ISSUE TITLE
Auth0.js v9 update breaks auth0-cordova

### ISSUE THREAD

**Issue by sebadoom** [auth0/auth0-cordova#64]
Auth0.js v9 changed the signature of one of the APIs used by auth0-cordova.

API change: 

https://github.com/auth0/auth0.js/commit/06e6860188128286454d1c48fe00278f6d75fa83#diff-757cd8fb74b000a4da9ea0fd33713c52R28

Notice the `auth0` argument added in front of the `options` argument.

auth0-cordova uses this in: https://github.com/auth0/auth0-cordova/blob/master/src/index.js#L33

This causes the `options` parameter to be used in place of the new `auth0` parameter, resulting in an exception in auth0.js, preventing instantiation of the Auth0Cordova object (and thus use of the library).

For example, this application has stopped working after updating the dependencies to auth0.js v9:

https://github.com/auth0-blog/ionic-got

**Comment by darkyen** [comment]
I am looking at it.

**Comment by darkyen** [comment]
Fixed by #65
