### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by eblancperso** [auth0/auth0-cordova#66]
Hello, I have followed every steps of this tutorial: https://auth0.com/docs/quickstart/native/ionic2 . I can access the login page and I can also login successfully (logs in my client are displaying "Success Login" with the proper user) but right after, I get a "Safari cannot open the page because the address is invalid". When I open the url in safari (not in the web view in ionic), I'm getting "Oops!, something went wrong" in https://mydomain.auth0.com/login/callback .Here are some code samples I'm using:

auth.service.ts
```
const auth0Config = {
    // needed for auth0
    clientID: 'my client id is here',

    // needed for auth0cordova
    clientId: 'my client id is here',
    domain: 'mydomain.auth0.com',
    callbackURL: location.href,
    packageIdentifier: 'io.ionic.starter'
};
```
config.xml
```
<plugin name="cordova-plugin-customurlscheme" spec="^4.3.0">
        <variable name="URL_SCHEME" value="io.ionic.starter" />
        <variable name="ANDROID_SCHEME" value="io.ionic.starter" />
        <variable name="ANDROID_HOST" value="mydomain.auth0.com" />
        <variable name="ANDROID_PATHPREFIX" value="/cordova/io.ionic.starter/callback" />
    </plugin>
```

package.json
```
"cordova": {
    "plugins": {
      "cordova-plugin-safariviewcontroller": {},
      "cordova-plugin-customurlscheme": {
        "URL_SCHEME": "io.ionic.starter",
        "ANDROID_SCHEME": "io.ionic.starter",
        "ANDROID_HOST": "mydomain.auth0.com",
        "ANDROID_PATHPREFIX": "/cordova/io.ionic.starter/callback"
      },
      "ionic-plugin-keyboard": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {}
    },
    "platforms": [
      "ios"
    ]
  }
```

I'm using:
```
"@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@auth0/cordova": "^0.3.0",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/pro": "1.0.16",
    "@ionic/storage": "2.1.3",
    "auth0-js": "^9.0.2",
    "cordova-ios": "4.5.4",
    "cordova-plugin-customurlscheme": "^4.3.0",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-inappbrowser": "^2.0.1",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-safariviewcontroller": "~1.5.2",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-whitelist": "1.3.1",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"

```

My client in auth0 is configured properly:
Domain: mydomain.auth0.com
ClientType: Native
Allowed Callback URLs: io.ionic.starter://mydomain.auth0.com/cordova/io.ionic.starter/callback
Allowed Origins (CORS): file://*

Last thing, i'm trying this with Ionic DevApp for iOS

I just don't know what to do with this!

Thank you

**Comment by immortal-88** [comment]
exactly same problem i have

**Comment by aec4444** [comment]
Same problem for me using Ionic DevApp.    Any help????

**Comment by dcxn** [comment]
Not sure if it helps, because I'm not using the dev app, but I had a similar issue. Turned out to be a wrong URL Scheme on [info settings in XCode](https://i.stack.imgur.com/Nq6qQ.png) when running the app. I added my correct url scheme and it worked.

**Comment by darkyen** [comment]
@aec4444 The Ionic Dev App does not deploy the custom plugins needed for this app to work. Therefore, it'll not work with the Ionic Dev App, you'll need to deploy on device for this to work or build a custom fork of the ionic dev app

**Comment by eblancperso** [comment]
@darkyen  Oh! That is why... I wonder if this information is mentioned somewhere?

**Comment by darkyen** [comment]
I am adding this to the readme.
