### ISSUE TITLE
Timing has changed in authorize method, results in hung login when already logged in to IDP.

### ISSUE THREAD

**Issue by davidemerritt** [auth0/auth0-cordova#67]
Not sure what has changed but this was working roughly a month ago. 

I'm using google-oauth2 as the connection type. 

When the user has already logged in once so google remembers the login the timing becomes screwed up and the onRedirectUri callback is triggered too soon.
```

CordovaAuth.onRedirectUri = function (url) {
  session.onRedirectUri(url);
};

```
The timing becomes. 

CordovaAuth.prototype.Authorize ->
getAgent ->
agent.open ->
(opened event) - which is skipped via `// if (result.event !== 'loaded') { return; } `
onRedirectUri (has no session.start method at this point)
(loaded event) - sets the session.start method but has no redirect trigger to work upon at this time.

I have no idea what changed but this was working a month ago. By allowing the opened event to set session.start (and also removing the session.start only occuring once check) it works as it used to. please advise, this is very troubling when my implementation didn't change.

**Comment by markkopaas** [comment]
When we started using "prompt:none" option, then similarly to @davidemerritt the /authorize page immediately redirects to callback, omitting the /login page. This ended up that redirect event happened before 'loaded'

When we set the session start to "opened", then the redirect handler was able to pick up the redirect url.

I don't understand how @davidemerritt you got several session.start? there is still only one "opened" event?

**Comment by darkyen** [comment]
I am looking into it at the moment.

**Comment by markkopaas** [comment]
@darkyen , we found, that in ios, there both 'opened' and 'loaded' happened, and the redirect handler was called right in between them. So, it was too late to register the redirect handler in 'loaded'. In android, however, the 'opened' event did not fire at all, only 'loaded'.
So for solution common to ios and android, we are now registering the redirect handler before opening the window, and extract the code from redirectUrl on 'loaded' event, which both platforms fire.

https://github.com/areo/auth0-cordova/commit/6eaa562b8a3d5e4bf5b3cfa77553c0023e213814

Lmk if this approach has any problems

**Comment by darkyen** [comment]
I don't see any obvious problems, I am discussing the issues with SafariViewControllers handling of these events internally and discussing our future plans for the plugin
