### ISSUE TITLE
Is this supposed to work on windows10 with cordova?

### ISSUE THREAD

**Issue by davidemerritt** [auth0/auth0-cordova#68]
I have not been able to get this to work with windows10, is this not supported? I am having several issues including a double loaded events within agent.open which cause the session.start to fail and the more-so, window.handleOpenURL is never called.

**Comment by darkyen** [comment]
The window.handleOpenURL method is implemented by cordova-plugin-customurischeme which only supports iOS and Android.

At the moment we do not support windows 10 apps, for UWP you'd ideally use https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.web it handles opening the URL and handles callbacks etc out of the box. 

For the most part the code can be shared from this lib however at https://github.com/auth0/auth0-cordova/blob/master/src/index.js#L95 you'll need to call the AuthenticationBroker and pass the response from it to onRedirectUri
