### ISSUE TITLE
auth0 cordova does not work on android4.4

### ISSUE THREAD

**Issue by davidemerritt** [auth0/auth0-cordova#70]
```Error in Success callbackId: SafariViewController1217950742 : TypeError: Object function Object() { [native code] } has no method 'assign' ```

Can you please document the versions for android this is supposed to support.

**Comment by davidemerritt** [comment]
This is because Android 4.4 doesn't support ES2015, it would just be good for you to document that somewhere in README

**Comment by ollyjohn** [comment]
Yeah I had a similar issue where I'd forked it because we needed different error messages and I put an arrow function in and it completely bricked our app for the few hours it took me to figure out what was causing it.  I'll take this one and update the README
