### ISSUE TITLE
Silent authentication - checkSession

### ISSUE THREAD

**Issue by markkopaas** [auth0/auth0-cordova#71]
Would it be possible to do silent authentication, without opening the browser window? Basically, what auth0-js checkSession does.
Right now we are using normal authentication with extra "prompt=none" attribute. This works, but It still opens browser and then quickly closes it.

This is the recommended way of refreshing access token without keeping the refresh_token

**Comment by luisrudge** [comment]
checkSession uses an iframe, so you still need a browser window to host the iframe. The only difference is that one opens a popup and the other doesn't. Can you use checkSession?

**Comment by darkyen** [comment]
For a native application like cordova you *should* get refresh_tokens and use them in order to refresh an access token. This refresh_token can further be stored in the device's keychain and cordova has libraries which provide access to the keychain / secure storage.
