### ISSUE TITLE
Error in Success callbackId: SafariViewController1328020603 : TypeError: crypto.randomBytes is not a function

### ISSUE THREAD

**Issue by stetsmando** [auth0/auth0-cordova#72]
Hello, I've got an existing angular cli project that we're converting to a Cordova project. Right now I'm moving our authentication over from using the `auth0-js` lib to the `auth0-cordova` plugin. I'm getting this error when attempting to call `.authorize()` on auth0 object `Error in Success callbackId: SafariViewController1328020603 : TypeError: crypto.randomBytes is not a function`.

I've tried testing on an emulator device running API version 27 and 26. I've also testing on a physical device running 8.1. All the same result.

I've added the `cordova-plugin-safariviewcontroller` and `cordova-plugin-customurlscheme` plugins.

The code I'm using to create the client looks like this:
```javascript
import Auth0Cordova from '@auth0/cordova';

// Class code...

public auth0Authentication = new Auth0Cordova({
    domain: AUTH_CONFIG.domain,
    clientId: AUTH_CONFIG.clientID,
    packageIdentifier: AUTH_CONFIG.packageID,
  });

// Other Code...

// Actual handler of the login button click
public login(): void {
console.log('Auth Service Login');
  const options = {
    scope: 'openid profile',
  };
  this.auth0Authentication.authorize(options, function (error, result) {
    if (error) {
      console.log(`Error with authentication: ${ JSON.stringify(error, null, 2) }`);
    }
    else {
      console.log(`Login result: ${ JSON.stringify(result, null, 2) }`);
    }
  });
}
```

Any help and or direction would be greatly appreciated.

**Comment by stetsmando** [comment]
After digging into this it appears that the file `src/crypto.js` was requiring `crypto` which has been deprecated. As such it was dying on any function calls to an empty object. I forked the repo and implemented a fix by simply requiring `crypto-browserify` and that resolved this issue. If there's any indication that this project gets attention from the maintainers I'd be happy to make a PR.

**Comment by darkyen** [comment]
The package relies on `https://nodejs.org/api/crypto.html` which should  be polyfilled by your build tool.

**Comment by stetsmando** [comment]
Rihgt but for some reason the angular cli, which is using webpack, isn't bundling that properly. I'm not really sure why that is, but what I've described has fixed the problem for me in the short term. Since I'm pretty sure that `crypto-browserify` is what's used for the polyfill anyways. Thanks for the reply 👍

**Comment by darkyen** [comment]
Check the build environment its targeting, it may be disabled in the webpack config file.
