### ISSUE TITLE
Android: Norton "Link Guard" issue

### ISSUE THREAD

**Issue by brassier** [auth0/auth0-cordova#74]
When an Android device has Norton Mobile Security installed, and specifically uses the "Link Guard" feature to open the Auth0 login page, I'm noticing an odd result.  The login succeeds but the app remains at the login page when it redirects back to the app.

Upon digging a little bit more it looks like something is triggering a "User Canceled" error prior to getting to the Auth0 login page.  However, the Auth0 login page still appears, and the login is able to succeed based on Auth0 logs.  But the Auth0 Cordova `authorize` callback does not get called with successful login info (likely because it was already called with a "User Canceled" error?)

**Comment by brassier** [comment]
Thanks @stetsmando .  Unfortunately I do already have AndroidLaunchMode set to singleTask in the `config.xml`.

**Comment by darkyen** [comment]
@brassier  That seems very weird, can you set a breakpoint and check if Norton is triggering a callback at the custom uri scheme for some reason?

**Comment by brassier** [comment]
@darkyen  - 

Per the instructions I am calling `authorize()` off the Auth0Cordova library (similar to below).  I set a breakpoint on this callback.  This callback is getting hit prior to the login page visually loading, with the `user canceled` error.  After the successful login this callback does not get called a second time (where it would normally get called with an auth result).  Seems like Norton may be loading the page, checking security, closing the page, then reloading the page?

    auth0.authorize(options, function (err, result) {
      if (err) {
        // failure
        if (err.message.includes("user canceled")) {
          this.loggingService.info("User cancelled login.");
        }
      }
      // success!
    });

**Comment by darkyen** [comment]
@brassier I figured the issue out, its androids event handling vs iOS event handling with cordova in the mix. I am currently re-writing the lib, to better handle these scenarios and offload more of this to nativeland. Apologies for the delay in this. 

> Seems like Norton may be loading the page, checking security, closing the page, then reloading the page?

Norton _shouldn't_ interfere with Auth0 / CCT flow here though.

**Comment by brassier** [comment]
That's great news @darkyen - thanks!  Looking forward to the new version.

**Comment by camhart** [comment]
Just FYI--I do not use Cordova Auth0--just android Auth0.  I'm still experiencing what I believe is the same problem.  Not sure if this is helpful or not, but leaving it in case someone else is searching and stumbles upon this.

**Comment by brassier** [comment]
Re: Stale Label - I don't believe this has been resolved.  I know we occasionally have to tell users to disable these Link Guard features.

**Comment by brassier** [comment]
Re: Stale Label - Once again, I don't believe this has been resolved.

**Comment by Widcket** [comment]
@lbalmaceda can you please try to repro this?

**Comment by lbalmaceda** [comment]
@brassier if **any** app is interfering with the redirect there's nothing this can do as an SDK to prevent that. On a separate note, I found that this feature [has been removed](https://twitter.com/NortonSupport/status/1218360584162271232) from Norton already.

**Comment by brassier** [comment]
@lbalmaceda - Good find on Link Guard being removed.  I'll close this since it's specific to that feature.
