### ISSUE TITLE
is TouchID login supported?

### ISSUE THREAD

**Issue by JohnMcLear** [auth0/auth0-cordova#79]
As per title, curious to know.  Assuming not but if it is that would be a huge bonus :)

**Comment by darkyen** [comment]
`TouchID` Is not an identification method as it does not share any details about the user but if the user has access to the device. Our iOS library has support for this via Credentials Manager which uses `TouchID` to validate access before reading from KeyChain. I am considering this for a future release in the library, however in the interim you should be able to use any keychain plugin from the `cordova-*` plugins to store and read tokens from KeyChain (there are ones that will allow you to do enforce touch-id aswell).
