### ISSUE TITLE
UI of the authentication page on Pixel 2

### ISSUE THREAD

**Issue by alegeza** [auth0/auth0-cordova#80]
Hello.
I understand that this issue is not a subject of the plugin, but could you please ask your frontend team to reduce the white space on authentication page?
Device: Pixel 2, Android 8.1

Small part of Login button is invisibile (picture 1)
When user enters invalid credentials error message is shown and login button gets completely invisible and user needs to scroll the page (picture 2)

![unnamed 1](https://user-images.githubusercontent.com/7292217/37212325-6a599ee2-23b7-11e8-805a-90da62dede7e.png)
![unnamed](https://user-images.githubusercontent.com/7292217/37212565-010b3e36-23b8-11e8-8a8d-e3e758f6fb69.png)

Thanks in advance

**Comment by darkyen** [comment]
Hi there, I posted this internally and we think as the hosted page is using Lock this should be moved to https://github.com/auth0/lock
