### ISSUE TITLE
WebDriver testing

### ISSUE THREAD

**Issue by JohnMcLear** [auth0/auth0-cordova#81]
Hey guys,

I use Webdriver to simulate user interactions and this causes problems as the safariviewcontroller is not available to the web driver.

Any suggestions how best to interact with it?

**Comment by darkyen** [comment]
Unfortunately, I don't think there is a good way to test this. I suppose you'd want to actually simulate an entire device and simulate interactions on that however, that'll be significantly more complicated than testing the web version.

**Comment by JohnMcLear** [comment]
@darkyen Worth leaving an issue open for this?  It might be just that we document a method for injecting a satisfactory access_token etc.

**Comment by darkyen** [comment]
I am thinking about ways to do so, just curious when using web-driver are you testing the app in Chrome?

**Comment by JohnMcLear** [comment]
It's Chrome > Safari > Chrome

Afaik!  Not sure tho -_-

**Comment by darkyen** [comment]
That complicates things a lot more, this library was designed to use PKCE w/ Code grant instead of `implicit` that you'd use for a browser. Theoretically you can use the inappbrowser plugin to simulate the same in Chrome / Safari.

**Comment by JohnMcLear** [comment]
I think by chrome I mean cordova WebKit > safari view controller > WebKit


________________________________
