### ISSUE TITLE
Usage with backend? 

### ISSUE THREAD

**Issue by lexaurin** [auth0/auth0-cordova#84]
Hi guys,

is there any way of how to use `auth0-cordova` in Cordova app which is just an UI for backend server application? As I understand from an API and examples, there is no such an option?

My usecase is - server backend (which has Auth0 client secret) and Cordova UI. I'd like to start auth flow on Auth0 Hosted Page, be redirected with `code` to backend, which with client secret exchanges it to valid access token. Cordova UI in this use case is not safe place to send access tokens. 

Why I'm asking, since Auth0 Lock is deprecated in Cordova (arguing with security), what is "the right" and more secure solution with Hosted Pages for cordova-backend app? Sending access tokens to UI?

**Comment by darkyen** [comment]
Sorry for the extremely late reply. Please use the https://community.auth0.com or https://support.auth0.com/ for architectural queries. Regarding the Question itself, the proper solution to this scenario is documented at https://auth0.com/docs/architecture-scenarios/mobile-api
