### ISSUE TITLE
Client.authorize callback returns error

### ISSUE THREAD

**Issue by kdbeall** [auth0/auth0-cordova#87]
Made an [issue here](https://github.com/auth0-samples/auth0-ionic3-samples/issues/3) but putting
it here as well. I was following this [Auth0 Tutorial](https://auth0.com/docs/quickstart/native/ionic3/01-login) When I go into my auth0 dashboard it shows a successful sign-in. However, ```err``` is returned back to the client-side. 

```
this.Client.authorize(options, (err, authResult) => {
      if (err) {
        let alert = this.alertCtrl.create({
          message: JSON.stringify(err)
        });
        alert.present();
        throw err;
      }
      /* Persist token to storage... */
```

Here's the JSON output from ```err```
```
{ "crossDomain": true, "method": "POST", "url": "https://myurl.auth0.com/oauth/token", "line":1, "column": 644436, "sourceURL":"http://localhost:8080/var/containers/Bundle/Application/..."},
"code":null, "description":null, "name": "Error"}
```

**Comment by kdbeall** [comment]
Okay, so I added localhost:8080 to my cross origins... seems to work now.

**Comment by alizafar** [comment]
@darkyen i have been reading your comments on related issues from earlier in the year. At one point you said it is not advisable to add localhost:8080 in Allowed Origins (CORS). So is there any other solution? I have just started with Ionic and installed the latest versions of everything, used the starter project and added the Auth0 piece following the Ionic3 quick start tutorial. I authenticate successfully but then the Auht0 logs report  Failed on CORS. I am using iOS via Xcode simulator and direct deploy on device. Adding the localhost entry resolves the problem. If this is not the right way, any feedback would be appreciated.

**Comment by darkyen** [comment]
> @darkyen i have been reading your comments on related issues from earlier in the year. At one point you said it is not advisable to add localhost:8080 in Allowed Origins (CORS). So is there any other solution?

Unfortunately not, the way Ionic works on iOS it is the only viable option. The other option is to migrate this library to nativeland.
