### ISSUE TITLE
Can't resolve 'crypto'

### ISSUE THREAD

**Issue by gregor-srdic** [auth0/auth0-cordova#88]
I am trying to use auth0-cordova in a Ionic4 project, and because it is using angular-cli@6 underneath, I am experiencing a simmilar problem:
Can't resolve 'crypto' in 'C:\Users\Nomnio\Workspace\Clausius\node_modules\@auth0\cordova\src'
any idea how to fix this?

**Comment by gregor-srdic** [comment]
seems I managed to fix the problem using this solution:
https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d

still I would appreciate some insight on what can be done to avoid the problem in the first place ... :)

**Comment by darkyen** [comment]
Crypto should Ideally be provided by Webpack or your build utility. I believe there was another issue that had the same issue, I expected the tool to be bundled in prod.

**Comment by fmflame** [comment]
I have the same issue and it is hard to work around...

**Comment by gianarb** [comment]
Hello! What's the current situation with this error? Should I relay on the script provided by @gregor-srdic ? Thanks

**Comment by maroldanvega07** [comment]
I tried the above script from @gregor-srdic but it doesn't work with ionic 4.12 and Angular 7.3.9. 
Any suggestions?

**Comment by Apeksha21** [comment]
I tried the solution from @gregor-srdic but it doesn't work with Ionic 4.4.2 and Angular 7.3.9. Can the issue be re-opened?

**Comment by jlacroix12** [comment]
This still presents problems in the recent versions of Ionic.   The script fixes things but the issue exists when trying to do a web deployment using the ionic dashboard.     The issue shouldn't be reopened.

**Comment by Apeksha21** [comment]
@jlacroix12 The script does not fix it for me and apparently for @maroldanvega07 also. I just don't want to create a duplicate issue.

**Comment by jlacroix12** [comment]
My apologize, i am still on 4.4.0 it may very well break the script on 4.4.2

**Comment by nyamage** [comment]
I got same problem but adding following to my package.json resolved the issue.

```
  "browser": {
    "crypto": false
  }
```

**Comment by ippeiukai** [comment]
This is near impossible to go around for Angular users without patching `@angular-devkit` packages inside the node_modules or going through lengthy custom webpack configuration.

Angular CLI does not support crypto for a good reason I believe.
https://github.com/angular/angular-cli/issues/1548#issuecomment-286151056

If a library is meant for browsers, like in this case as a cordova plugin, we really should use the crypto of the web world, not that of node.js.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API

**Comment by ippeiukai** [comment]
To anyone pathing inside their node_modules with postinstall, this is probably much cleaner solution:

https://github.com/auth0/auth0-cordova/issues/72#issuecomment-362174798
https://github.com/auth0/auth0-cordova/compare/master...stetsmando:master

**Comment by parliament718** [comment]
Why was this issue closed? Is every Angular user expected to moneypatch or fork this library?

**Comment by thesayyn** [comment]
I guess beloved developers of auth8 do not care about problems as a developer...

**Comment by ippeiukai** [comment]
Let's see...

https://github.com/auth0/auth0-cordova/issues/109

**Comment by parliament718** [comment]
I can't even get it to work with your fork solution @ippeiukai . The resolve crypto goes away bu then I get

ERROR in ./node_modules/browserify-sign/browser/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/user/Documents/code/rapsheet-mobile/node_modules/browserify-sign/browser'
ERROR in ./node_modules/cipher-base/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/user/Documents/code/rapsheet-mobile/node_modules/cipher-base'
ERROR in ./node_modules/hash-base/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/user/Documents/code/rapsheet-mobile/node_modules/hash-base'
[ERROR] An error occurred while running subprocess ng.

::sigh::

**Comment by ippeiukai** [comment]
@parliament718 Did you try switching from `@auth0/cordova` to `cordova-plugin-auth0` in your package.json and config.xml? I didn't try it on production myself, but looked promising.

**Comment by parliament718** [comment]
This was just released, so I'll just leave it here: https://auth0.com/docs/quickstart/native/ionic4/01-login

Looks like auth0 team finally came around to it. Will try soon and report back

**Comment by gregor-srdic** [comment]
this seems to be working for me quite some time now:
- create a folder "config" at the root of the project and put this code in "crypto_patch.js":
`
const fs = require('fs');
const f = 'node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js';
fs.readFile(f, 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  var result = data.replace(/node: false/g, 'node: {crypto: true, stream: true, fs: "empty"}');

  fs.writeFile(f, result, 'utf8', function (err) {
    if (err) return console.log(err);
  });
});
`
- add `"postinstall": "node ./config/crypto_patch.js"` to srcripts in package.json file

I believe that is all.

**Comment by hoanganhnino** [comment]
install webpack version 4.35.3, webpack-cli version 3.3.5 solve my problem
