### ISSUE TITLE
Auth0Cordova is not a constructor

### ISSUE THREAD

**Issue by joeflack4** [auth0/auth0-cordova#89]
I am trying to use auth0 in my Cordova app which also makes use of React. I’ve seen a tutorial for using auth0 with Cordova, and one for use with React, but none that combines both, so I’m kind of winging it.

When clicking my login button, I get the following error: `TypeError: __WEBPACK_IMPORTED_MODULE_1__auth0_cordova__.Auth0Cordova is not a constructor`

Here is are images of the stack trace:
<img width="641" alt="1" src="https://user-images.githubusercontent.com/13045020/44006665-f549027c-9e55-11e8-9ebc-7d60f3b29f81.png">
<img width="666" alt="2" src="https://user-images.githubusercontent.com/13045020/44006666-f555c1e2-9e55-11e8-9bda-7bbdc5bfadb5.png">

I’ve made a gist of the 3 relevant files here: https://gist.github.com/joeflack4/4b271a33a072ad097150374dfa304a68

Also posted this on the auth0 community:
https://community.auth0.com/t/getting-auth0cordova-is-not-a-constructor-when-using-auth0-for-react-cordova/14234

**Comment by joeflack4** [comment]
Nvm, fixed.

Issue was that I needed to change:
this: `import { Auth0Cordova } from '@auth0/cordova';`
--> 
to this: `import Auth0Cordova from '@auth0/cordova';`

**Comment by RobinBruneel** [comment]
Had the same error, I used `"module": "commonjs"` in my tsconfig instead of  `"module": "es2015"`, like in the auth0 sample project: https://github.com/auth0-samples/auth0-ionic3-samples/tree/master/01-Login
