### ISSUE TITLE
Require in example "Uncaught ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by JohnMcLear** [auth0/auth0-cordova#95]
If you follow the instructions step by step you are presented this error in console.

Afaik the issue is due to the assumption require will be available in the app.

I have a hacky workaround that I'm using but I'd prefer to use a fully documented implementation which doesn't *require* my hacks #dadJokes

**Comment by ddaaggeett** [comment]
may i have your hacky workaround? i may be having the same issue as you -> [https://github.com/ddaaggeett/podware/issues/1](https://github.com/ddaaggeett/podware/issues/1)

**Comment by darkyen** [comment]
You shouldn't install web pack with sudo. Assuming you have all the sub packages installed can also rely directly on `dist` (https://github.com/auth0/auth0-cordova/tree/master/dist).

**Comment by biswas123** [comment]
Can anyone teach how to use auth0 cordova without using webpack ?

**Comment by biswas123** [comment]
Why is that this example uses webpack,  I have no knowledge of webpack and there are many users like me who don't use webpack..

**Comment by biswas123** [comment]
Can anyone help me please, I need help desperately.

**Comment by darkyen** [comment]
Hey Biswas, as I mentioned you should be able to just the bundle in `dist/`. However, you'll still need to install the dependencies via cordova.

**Comment by biswas123** [comment]
okay thanks. I solved it using dist.
